title: My Website
description: A personal website built with GitHub Pages and Jekyll
theme: minima

url: "https://matthew-w-self.github.io"
baseurl: "/self-lab"

markdown: kramdown

header_pages:
  - index.md

plugins:
  - jekyll-feed
