title: Self Lab
description: Research in neuroscience, perception, and cognition
theme: minima

url: "https://matthew-w-self.github.io"
baseurl: "/self-lab"

markdown: kramdown

header_pages:
  - index.md
  - members.md
  - research.md
  - contact.md

plugins:
  - jekyll-feed
